### PR TITLE
clipboard: fix Linux compilation when Gnome isn't available

### PR DESCRIPTION
**Pull request by jonruttan**
This pull request addresses an error when compiling on Linux without Gnome due to missing definitions for `e_clipboard_copy` and `e_clipboard_paste`.

```sh
make
mkdir -p /home/user/.estx
cp stx/* /home/user/.estx
DE is ubuntu
mkdir -p bin/
cc main.c src/clipboard.c src/editor.c src/buffer.c src/util.c src/colors.c src/syntax.c -DSTXDIR=\"/home/user/.estx\" -o bin/e -Werror -Wall -g -fPIC -O2 -DNDEBUG -ftrapv -Wfloat-equal -Wundef -Wwrite-strings -Wuninitialized -pedantic -std=c11
/tmp/ccmLhwOf.o: In function `e_initial':
/home/usr/src/e/src/editor.c:509: undefined reference to `e_clipboard_copy'
/home/usr/src/e/src/editor.c:490: undefined reference to `e_clipboard_copy'
/home/usr/src/e/src/editor.c:512: undefined reference to `e_clipboard_paste'
collect2: error: ld returned 1 exit status
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 1
```

### CODE REVIEW

**Comment by hellerve** [comment]
Oh! I suppose that’s a regression introduced by #32. Good catch, thanks!
